--
-- PostgreSQL database dump
--

\restrict hmdfy6vqM37du1iVsazNv9thalShDOdJI2AoiusKn8ZQM2HmeB6Mt3Z3ZemDaLO

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: campaigns; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.campaigns (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    address character varying(255) NOT NULL,
    category character varying(255),
    city character varying(255) NOT NULL,
    deadline timestamp(6) without time zone,
    description character varying(255),
    location character varying(255),
    media_urls character varying(255),
    owner_type character varying(255) NOT NULL,
    state character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    target_amount double precision,
    title character varying(255),
    urgency character varying(255),
    owner_id bigint NOT NULL,
    image_url character varying(255),
    CONSTRAINT campaigns_owner_type_check CHECK (((owner_type)::text = ANY ((ARRAY['NGO'::character varying, 'INDIVIDUAL'::character varying])::text[]))),
    CONSTRAINT campaigns_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying, 'EXPIRED'::character varying])::text[])))
);


ALTER TABLE public.campaigns OWNER TO postgres;

--
-- Name: campaigns_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.campaigns ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.campaigns_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: donation_certificates; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.donation_certificates (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    certificate_id character varying(255),
    donation_amount bigint,
    issued_date date,
    assignment_id bigint NOT NULL,
    donor_id bigint NOT NULL,
    receiver_id bigint NOT NULL
);


ALTER TABLE public.donation_certificates OWNER TO postgres;

--
-- Name: donation_certificates_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.donation_certificates ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.donation_certificates_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: donation_offers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.donation_offers (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    age_group character varying(255),
    amount bigint,
    donation_category character varying(255),
    gender character varying(255),
    location character varying(255),
    preferred_contact character varying(255),
    reason character varying(255),
    recurring_help boolean NOT NULL,
    status character varying(255) NOT NULL,
    time_line character varying(255),
    type character varying(255),
    user_id bigint NOT NULL,
    CONSTRAINT donation_offers_status_check CHECK (((status)::text = ANY ((ARRAY['OPEN'::character varying, 'ASSIGNED'::character varying, 'IN_PROGRESS'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying, 'EXPIRED'::character varying])::text[])))
);


ALTER TABLE public.donation_offers OWNER TO postgres;

--
-- Name: donation_offers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.donation_offers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.donation_offers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: gallery; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.gallery (
    id bigint NOT NULL,
    caption character varying(255),
    image_path character varying(255) NOT NULL,
    status character varying(255),
    uploaded_at timestamp(6) without time zone,
    ngo_id bigint NOT NULL,
    CONSTRAINT gallery_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


ALTER TABLE public.gallery OWNER TO postgres;

--
-- Name: gallery_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.gallery ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gallery_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: gallery_images; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.gallery_images (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    approved boolean NOT NULL,
    caption character varying(255),
    image_url character varying(255) NOT NULL,
    ngo_id bigint NOT NULL
);


ALTER TABLE public.gallery_images OWNER TO postgres;

--
-- Name: gallery_images_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.gallery_images ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gallery_images_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: help_request_entity; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.help_request_entity (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    age_group character varying(255),
    amount_required bigint,
    category character varying(255),
    gender character varying(255),
    location character varying(255),
    reason character varying(255),
    requested_by bigint,
    requester_type character varying(255),
    type_of_help character varying(255),
    urgency character varying(255),
    user_id bigint NOT NULL
);


ALTER TABLE public.help_request_entity OWNER TO postgres;

--
-- Name: help_request_entity_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.help_request_entity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.help_request_entity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: moderator_assignments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.moderator_assignments (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    receiver_type character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    donation_request_id bigint NOT NULL,
    donor_id bigint NOT NULL,
    moderator_id bigint NOT NULL,
    receiver_id bigint NOT NULL,
    CONSTRAINT moderator_assignments_receiver_type_check CHECK (((receiver_type)::text = ANY ((ARRAY['INDIVIDUAL'::character varying, 'CSR_COMPANIES'::character varying, 'NGO'::character varying, 'MODERATOR'::character varying])::text[])))
);


ALTER TABLE public.moderator_assignments OWNER TO postgres;

--
-- Name: moderator_assignments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.moderator_assignments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.moderator_assignments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ngo_profiles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ngo_profiles (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    account_holder_name character varying(255),
    activation_status character varying(255),
    address_line text,
    bank_account character varying(255),
    bank_name character varying(255),
    categories character varying(255),
    city character varying(255),
    description text,
    documents_json text,
    email character varying(255),
    ifsc character varying(255),
    ngo_name character varying(255),
    pan character varying(255),
    phone character varying(255),
    pincode character varying(255),
    registration_number character varying(255),
    registration_type character varying(255),
    state character varying(255),
    user_id bigint NOT NULL,
    address text,
    district character varying(255),
    CONSTRAINT ngo_profiles_activation_status_check CHECK (((activation_status)::text = ANY ((ARRAY['PENDING'::character varying, 'VERIFIED'::character varying, 'REJECTED'::character varying])::text[])))
);


ALTER TABLE public.ngo_profiles OWNER TO postgres;

--
-- Name: ngo_profiles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ngo_profiles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ngo_profiles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    company_name character varying(255),
    corporate_id character varying(255),
    email character varying(255),
    encrypted_password character varying(255) NOT NULL,
    first_name character varying(255),
    full_name character varying(255) NOT NULL,
    govt_certificate_number character varying(255),
    is_verified boolean NOT NULL,
    last_name character varying(255),
    mobile_number character varying(255) NOT NULL,
    ngo_registration_id character varying(255),
    organisation_name character varying(255),
    profile_completed boolean NOT NULL,
    role character varying(255) NOT NULL,
    user_type character varying(255) NOT NULL,
    address_line character varying(255),
    city character varying(255),
    pincode character varying(255),
    profession character varying(255),
    state character varying(255),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying, 'MODERATOR'::character varying, 'SUPER_ADMIN'::character varying])::text[]))),
    CONSTRAINT users_user_type_check CHECK (((user_type)::text = ANY ((ARRAY['INDIVIDUAL'::character varying, 'CSR_COMPANIES'::character varying, 'NGO'::character varying, 'MODERATOR'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: campaigns campaigns_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campaigns
    ADD CONSTRAINT campaigns_pkey PRIMARY KEY (id);


--
-- Name: donation_certificates donation_certificates_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.donation_certificates
    ADD CONSTRAINT donation_certificates_pkey PRIMARY KEY (id);


--
-- Name: donation_offers donation_offers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.donation_offers
    ADD CONSTRAINT donation_offers_pkey PRIMARY KEY (id);


--
-- Name: gallery_images gallery_images_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gallery_images
    ADD CONSTRAINT gallery_images_pkey PRIMARY KEY (id);


--
-- Name: gallery gallery_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gallery
    ADD CONSTRAINT gallery_pkey PRIMARY KEY (id);


--
-- Name: help_request_entity help_request_entity_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.help_request_entity
    ADD CONSTRAINT help_request_entity_pkey PRIMARY KEY (id);


--
-- Name: moderator_assignments moderator_assignments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.moderator_assignments
    ADD CONSTRAINT moderator_assignments_pkey PRIMARY KEY (id);


--
-- Name: ngo_profiles ngo_profiles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ngo_profiles
    ADD CONSTRAINT ngo_profiles_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: ngo_profiles ukcm3ygmaf6ywhpqqmb0ypcplj5; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ngo_profiles
    ADD CONSTRAINT ukcm3ygmaf6ywhpqqmb0ypcplj5 UNIQUE (user_id);


--
-- Name: donation_certificates ukpp6a5kr0erhrrn4f3b79i7826; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.donation_certificates
    ADD CONSTRAINT ukpp6a5kr0erhrrn4f3b79i7826 UNIQUE (assignment_id);


--
-- Name: users ukr7c96a004bv8w16jgdm8imich; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr7c96a004bv8w16jgdm8imich UNIQUE (mobile_number);


--
-- Name: donation_certificates uksfgefbsd4dcfqrbyxnowxeko3; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.donation_certificates
    ADD CONSTRAINT uksfgefbsd4dcfqrbyxnowxeko3 UNIQUE (certificate_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: donation_certificates fk14v4g2chmo0l393a6lccqk9vv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.donation_certificates
    ADD CONSTRAINT fk14v4g2chmo0l393a6lccqk9vv FOREIGN KEY (donor_id) REFERENCES public.users(id);


--
-- Name: donation_certificates fk1pw883riir6197nh2a56pyqb6; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.donation_certificates
    ADD CONSTRAINT fk1pw883riir6197nh2a56pyqb6 FOREIGN KEY (receiver_id) REFERENCES public.users(id);


--
-- Name: moderator_assignments fk5idemqo0yuts326ywmmlqly37; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.moderator_assignments
    ADD CONSTRAINT fk5idemqo0yuts326ywmmlqly37 FOREIGN KEY (moderator_id) REFERENCES public.users(id);


--
-- Name: ngo_profiles fkex1441h9cjm3djs5vmdycfhqn; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ngo_profiles
    ADD CONSTRAINT fkex1441h9cjm3djs5vmdycfhqn FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: donation_offers fkfxd6p3heedi5av76m8ollswjs; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.donation_offers
    ADD CONSTRAINT fkfxd6p3heedi5av76m8ollswjs FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: gallery_images fkhdhhwgbomns7dh7siq18dfndx; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gallery_images
    ADD CONSTRAINT fkhdhhwgbomns7dh7siq18dfndx FOREIGN KEY (ngo_id) REFERENCES public.users(id);


--
-- Name: moderator_assignments fkid6e6qjh9eea2w4wqw45g602f; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.moderator_assignments
    ADD CONSTRAINT fkid6e6qjh9eea2w4wqw45g602f FOREIGN KEY (donation_request_id) REFERENCES public.donation_offers(id);


--
-- Name: donation_certificates fkokglmx5xcur5rh4lx655wknhi; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.donation_certificates
    ADD CONSTRAINT fkokglmx5xcur5rh4lx655wknhi FOREIGN KEY (assignment_id) REFERENCES public.moderator_assignments(id);


--
-- Name: gallery fkply6h9je23hmef9toltjkvwuk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.gallery
    ADD CONSTRAINT fkply6h9je23hmef9toltjkvwuk FOREIGN KEY (ngo_id) REFERENCES public.users(id);


--
-- Name: campaigns fkppm1bi09wp1gwlyi876acgbn; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.campaigns
    ADD CONSTRAINT fkppm1bi09wp1gwlyi876acgbn FOREIGN KEY (owner_id) REFERENCES public.users(id);


--
-- Name: moderator_assignments fkrbs274d31s8efi2mkcros79hc; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.moderator_assignments
    ADD CONSTRAINT fkrbs274d31s8efi2mkcros79hc FOREIGN KEY (donor_id) REFERENCES public.users(id);


--
-- Name: moderator_assignments fktjknquwn7yl3qv7q84djp08tk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.moderator_assignments
    ADD CONSTRAINT fktjknquwn7yl3qv7q84djp08tk FOREIGN KEY (receiver_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--

\unrestrict hmdfy6vqM37du1iVsazNv9thalShDOdJI2AoiusKn8ZQM2HmeB6Mt3Z3ZemDaLO

