package com.prerana.userservice.enums;

public enum FeatureKey {
    HELP_REQUEST_LIMIT,
    VOLUNTEER_REQUEST_LIMIT,
    PRIORITY_MATCHING,
    DONATION_LIMIT,
    PRIORITY_ASSIGNMENT,
    CAMPAIGN_CREATE,
    ACTIVE_CAMPAIGNS,
    PROFILE_VISIBILITY,
    CSR_HELP_ASSIGN_PRIORITY,
    CSR_MAX_ACTIVE_ASSIGNMENTS,
    FAST_TRACK_ASSIGNMENT
}
